version: '3.8'
services:
  kafka1:
    deploy:
      placement:
        constraints:
          - node.labels.node == src
    image: rehanchy/kafka:kafka-acl-2.13.2.6.1-1
    hostname: kafka1
    networks:
      - vnetwork
    environment:
      - BROKER_ID=1
      - KAFKA_BROKERS=kafka1:9092,kafka2:9092,kafka3:9092
      - ZOOKEEPER_SERVERS=zookeeper1:2181

  kafka2:
    deploy:
      placement:
        constraints:
          - node.labels.node == src
    image: rehanchy/kafka:kafka-acl-2.13.2.6.1-1
    hostname: kafka2
    networks:
      - vnetwork
    environment:
      - BROKER_ID=2
      - KAFKA_BROKERS=kafka1:9092,kafka2:9092,kafka3:9092
      - ZOOKEEPER_SERVERS=zookeeper1:2181

  kafka3:
    deploy:
      placement:
        constraints:
          - node.labels.node == src
    image: rehanchy/kafka:kafka-acl-2.13.2.6.1-1
    hostname: kafka3
    networks:
      - vnetwork
    environment:
      - BROKER_ID=3
      - KAFKA_BROKERS=kafka1:9092,kafka2:9092,kafka3:9092
      - ZOOKEEPER_SERVERS=zookeeper1:2181
  kafka4:
    deploy:
      placement:
        constraints:
          - node.labels.node == dest
    image: rehanchy/kafka:kafka-acl-2.13.2.6.1-1
    hostname: kafka4
    networks:
      - vnetwork
    environment:
      - BROKER_ID=4
      - KAFKA_BROKERS=kafka4:9092,kafka5:9092,kafka6:9092
      - ZOOKEEPER_SERVERS=zookeeper2:2181

  kafka5:
    deploy:
      placement:
        constraints:
          - node.labels.node == dest
    image: rehanchy/kafka:kafka-acl-2.13.2.6.1-1
    hostname: kafka5
    networks:
      - vnetwork
    environment:
      - BROKER_ID=5
      - KAFKA_BROKERS=kafka4:9092,kafka5:9092,kafka6:9092
      - ZOOKEEPER_SERVERS=zookeeper2:2181

  kafka6:
    deploy:
      placement:
        constraints:
          - node.labels.node == dest
    image: rehanchy/kafka:kafka-acl-2.13.2.6.1-1
    hostname: kafka6
    networks:
      - vnetwork
    environment:
      - BROKER_ID=6
      - KAFKA_BROKERS=kafka4:9092,kafka5:9092,kafka6:9092
      - ZOOKEEPER_SERVERS=zookeeper2:2181
networks:
  vnetwork:
    external: true